### ISSUE TITLE
Isn't it doing the job?

### ISSUE THREAD

**Issue by thom4parisot** [DavidBruant/columns#2]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/138627/51374729-2e2c8700-1b04-11e9-9e41-cd3250ca300c.png">

Looks like you need to have repo admin permissions to do so (write permissions are not sufficient).

**Comment by DavidBruant** [comment]
> Isn't **it** doing the job?

> Looks like you need to have repo admin permissions to do **so**

I do not understand the highlighted words

**Comment by thom4parisot** [comment]
_it_ → the "Transfer issue [beta]" link.

_permissions to do so_ → to do the issue transfer.

**Comment by DavidBruant** [comment]
issue transfer is from one repository to another\
what i'm doing here is transfering (copying) issues/cards from one github project to another

**Comment by thom4parisot** [comment]
Aaaaah. My bad!

**Comment by thom4parisot** [comment]
I think I got confused by reading this bit of the project description: "Transfer cards/issues", so I pointed out the "issue transfer link".
